name: Build All

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:
    # allows manual trigger

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnetversion: ['net8.0', 'net9.0']
        projname: [ 'EIV_Core', 'EIV_Modules' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clone EIV Nuget repository
      uses: actions/checkout@v4
      with:
        repository: ExtractIntoVoid/Nuget
        path: eiv_nuget
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Add eiv_nuget to nuget souce
      run: dotnet nuget add source --name eiv_nuget $env:GITHUB_WORKSPACE/eiv_nuget

    - name: Publish
      run: dotnet publish ${{ matrix.projname }}/${{ matrix.projname }}.csproj -c Release -f ${{ matrix.dotnetversion }} -o Out
  
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.projname }}
        path: Out
        if-no-files-found: error